name: Setup ossutil

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: manyuanrong/setup-ossutil@master
      with:
        endpoint: "oss-cn-qingdao.aliyuncs.com"
        access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
    - run: ossutil -h
    - run: echo $GITHUB_SHA > output.txt
    - run: ossutil cp output.txt oss://enok-code/ossutil.txt -f